version: '3.8'

services:
  postgres:
    build: ./database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  etl:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    volumes:
      - ./etl:/app/etl
      - ./data:/app/data
    working_dir: /app
    command: ["python", "etl/etl.py"]
    env_file:
      - .env
    restart: "no"

volumes:
  postgres-data:
